pipeline {
    agent any
    stages {
        stage("Build"){
            steps{
                dir("algorithms-majn"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("algorithms-majn"){
                    sh "mvn test"
                }
            }
        }
    }
}